version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      workflow:
        patterns:
          - "*"
    assignees:
      - "krymtkts"
    reviewers:
      - "krymtkts"
  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      dotnet-tools:
        patterns:
          - "fable"
          - "femto"
      fable:
        patterns:
          - "Fable.*"
          - "Feliz"
    assignees:
      - "krymtkts"
    reviewers:
      - "krymtkts"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      marked:
        dependency-type: "production"
        exclude-patterns:
          - "react*" # NOTE: react should be updated with Fable.
        exclude-patterns:
          - "marked*"
          - "highlight.js"
      dev-dependencies:
        dependency-type: "development"
    assignees:
      - "krymtkts"
    reviewers:
      - "krymtkts"
