version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Asia/Tokyo"
    groups:
      workflow:
        patterns:
          - "*"
    assignees:
      - "krymtkts"
  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directories:
      - "/.config"
      - "/src"
      - "/test"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Asia/Tokyo"
    groups:
      dotnet-tools:
        patterns:
          - "fable"
          - "fantomas"
          - "femto"
      fable:
        patterns:
          - "Fable.*"
          - "Feliz"
      test:
        exclude-patterns:
          - "fable"
          - "fantomas"
          - "femto"
          - "Fable.*"
          - "Feliz"
        patterns:
          - "*"
    assignees:
      - "krymtkts"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Asia/Tokyo"
    groups:
      dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "react*"
      react-dependencies:
        dependency-type: "production"
        patterns:
          - "react*"
      dev-dependencies:
        dependency-type: "development"
    assignees:
      - "krymtkts"
